pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Sonarqube'){
            steps{
                dir(env.WORKSPACE){
                    sh "mvn sonar:sonar \
                          -Dsonar.projectKey=net.shuzun:product-parent \
                          -Dsonar.host.url=http://192.168.40.134:9000 \
                          -Dsonar.login=0c498dd24176db710f205a82af47564cb11c178e"
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
